## 飞机参数
Quad:
  mass: 1.0
  throttle_a: 20.0
  throttle_b: 0.0

##geo fence
geo_fence:
  x_min: -2.0
  x_max: 2.0
  y_min: -2.0
  y_max: 2.0
  z_min: -0.5
  z_max: 3.0

## 限制参数
Limit:
  tilt_max: 20.0
  THR_MIN: 0.1
  THR_MAX: 0.9
  XY_VEL_MAX : 0.8
  Z_VEL_MAX : 0.5

## 起飞高度
Takeoff_height : 0.8
Disarm_height : 0.15

# 位置环参数
Pos_pid:
  Kp_xy : 0.95
  Kp_z : 1.0
  Kp_vxvy : 0.09
  Kp_vz : 0.2
  Ki_vxvy : 0.02
  Ki_vz : 0.02
  Kd_vxvy : 0.01
  Kd_vz : 0.00
  Hover_throttle : 0.5
  MPC_VELD_LP: 5.0

# 位置环参数 for ude
Pos_ude:
  Kp_xy : 0.5
  Kp_z : 0.5
  Kd_xy : 2.0
  Kd_Zz : 2.0
  T_ude_xy : 1.0
  T_ude_z : 1.0
  INT_LIM_X : 5.0
  INT_LIM_Y : 5.0
  INT_LIM_Z : 10.0

# 位置环参数 for passivity
Pos_passivity:
  Kp_xy : 0.5
  Kp_z : 0.5
  Kd_xy : 2.0
  Kd_z : 2.0
  T_ude_xy : 1.0
  T_ude_z : 1.0
  T1: 0.1
  INT_LIM_X : 5.0
  INT_LIM_Y : 5.0
  INT_LIM_Z : 10.0

# 位置环参数 for ne
Pos_ne:
  Kp_xy : 0.5
  Kp_z : 0.5
  Kd_xy : 2.0
  Kd_z : 2.0
  T_ude_xy : 1.0
  T_ude_z : 1.0
  Tn: 0.1
  INT_LIM_X : 5.0
  INT_LIM_Y : 5.0
  INT_LIM_Z : 10.0






